export const HANDLE_FIRST_SELECT = 'HANDLE_FIRST_SELECT';
export const HANDLE_SECOND_SELECT = 'HANDLE_SECOND_SELECT';
export const HANDLE_THIRD_SELECT = 'HANDLE_THIRD_SELECT';
export const HANDLE_INPUT = 'HANDLE_INPUT';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_FAIL = 'FETCH_DATA_FAIL';
export const HANDLE_SECOND_INPUT = 'HANDLE_SECOND_INPUT';
